# Generated by Django 5.1.2 on 2024-10-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_social_github_profile_social_linkedin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='user',
            new_name='profile',
        ),
    ]
