# Generated by Django 5.1.2 on 2024-10-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_skills_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='bg_color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AddField(
            model_name='skills',
            name='fg_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
