# Generated by Django 5.1.2 on 2024-12-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_chatrecords_message_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='testing',
        ),
        migrations.AddField(
            model_name='user',
            name='socket_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
