# Generated by Django 5.1.2 on 2024-12-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_skills_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='short_bio',
            new_name='bio',
        ),
    ]
