# Generated by Django 5.1.2 on 2024-12-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_short_bio_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatars/default.png', upload_to='avatars/'),
        ),
    ]
