# Generated by Django 5.1.2 on 2024-10-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
