# Generated by Django 5.1.2 on 2024-10-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='poster',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/330px-No-Image-Placeholder.svg.png?20200912122019'),
        ),
    ]
