# Generated by Django 5.1.2 on 2024-10-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='poster',
            field=models.ImageField(blank=True, default='posters/default.png', null=True, upload_to='posters/'),
        ),
    ]
