# Generated by Django 5.1.2 on 2024-10-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
        migrations.AlterField(
            model_name='project',
            name='poster',
            field=models.ImageField(default='posters/default.jpg', upload_to='posters/'),
        ),
    ]
