# Generated by Django 5.1.2 on 2024-11-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=range(1, 6)),
        ),
    ]
